spring:
  application:
    name: serverconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nicolos-Cheung/SpringCloud-Config-List
          username: 349719588@qq.com
          password: lu97j9i88
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/
server:
  port: 8080